# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-17 16:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='weborder',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 10, 17, 19, 31, 4, 95474)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weborder',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courrier.Status'),
        ),
    ]
