# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0003_auto_20171017_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weborder',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='weborder',
            name='zip_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
