# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixed_costs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('total_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_dept', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fixed_Costs_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('total_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_dept', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcations.Fixed_costs')),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Απασχόληση')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Σημειώσεις')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Συνολικά Έξοδα')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcations.Fixed_costs')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Fixed_Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Αρ.Παραστατικού')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Λήξης')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Αξία')),
                ('credit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Υπόλοιπο')),
                ('active', models.CharField(choices=[('a', 'Απλήρωτη'), ('b', 'Πληρώθηκε')], default='a', max_length=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcations.Fixed_Costs_item', verbose_name='Λογαριασμός')),
            ],
        ),
        migrations.CreateModel(
            name='PayOrderFixedCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Αρ.Παραστατικού')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Πληρωμής')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Αξία')),
            ],
        ),
        migrations.CreateModel(
            name='PayPersonFixedCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Ονοματεπώνυμο')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Ονοματεπώνυμο')),
                ('phone', models.IntegerField(max_length=10, verbose_name='Τηλέφωνο')),
                ('phone1', models.IntegerField(max_length=10, verbose_name='Κινητό')),
                ('date_joined', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Πρόσληψης')),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Βασικός Μισθός')),
                ('weekly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Εβδομαδαιίος Μισθός')),
                ('day_salary', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Ημερομισθιο')),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Συνολική Πληρωμή')),
                ('times_per_month', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Υπερωρίες')),
                ('hour_salary', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Ωρομίσθιο')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcations.Occupation', verbose_name='Απασχόληση')),
            ],
        ),
    ]
