# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PayPersonFixedCost',
            new_name='PayPersonBasicSalaryCost',
        ),
        migrations.AddField(
            model_name='person',
            name='day_salary_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Υπόλοιπο Ημερομησθίων'),
        ),
        migrations.AddField(
            model_name='person',
            name='hour_salary_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Υπόλοιπο Υπερωρίων'),
        ),
        migrations.AddField(
            model_name='person',
            name='monthly_salary_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Υπόλοιπο Βασικού Μισθού'),
        ),
        migrations.AddField(
            model_name='person',
            name='salary_remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Συνολικό Υπόλοιπο'),
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('a', 'Ενεργός'), ('b', 'Μη Ενεργός')], default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='person',
            name='weekly_salary_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Υπόλοιπο Εβδομαδιαίου Μισθού'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='Τηλέφωνο'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone1',
            field=models.CharField(max_length=10, verbose_name='Κινητό'),
        ),
    ]
