# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-28 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcations', '0004_paypersondailycost_paypersonhours_paypersonweeklycost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PayPersonWeeklyCost',
            new_name='PayPersonIkaCost',
        ),
    ]
