# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transcations', '0005_auto_20160528_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPersonPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CreatePersonSalaryCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Περιγραφή')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Αξία')),
                ('day_added', models.DateField(auto_now=True)),
                ('day_expire', models.DateField(default=django.utils.timezone.now, verbose_name='Πληρωμή μέχρι .....')),
                ('status', models.CharField(choices=[('a', 'Ενεργός'), ('b', 'Μη Ενεργός')], default='a', max_length=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcations.CategoryPersonPay', verbose_name='Είδος Πληρωμής')),
            ],
        ),
        migrations.CreateModel(
            name='PayPersonSalaryCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Περιγραφή')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Αξία')),
                ('day_added', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcations.CategoryPersonPay', verbose_name='Είδος Πληρωμής')),
            ],
        ),
        migrations.CreateModel(
            name='PersonHoursCreate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Περιγραφή')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Αξία')),
                ('day_added', models.DateField(auto_now=True)),
                ('day_expire', models.DateField(default=django.utils.timezone.now, verbose_name='Πληρωμή μέχρι .....')),
                ('status', models.CharField(choices=[('a', 'Ενεργός'), ('b', 'Μη Ενεργός')], default='a', max_length=1)),
                ('times_per_month', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Υπερωρίες')),
                ('hour_salary', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Ωρομίσθιο')),
            ],
        ),
        migrations.CreateModel(
            name='PersonHoursPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Περιγραφή')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Αξία')),
                ('day_added', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PayPersonBasicSalaryCost',
        ),
        migrations.DeleteModel(
            name='PayPersonDailyCost',
        ),
        migrations.DeleteModel(
            name='PayPersonHours',
        ),
        migrations.DeleteModel(
            name='PayPersonIkaCost',
        ),
        migrations.RemoveField(
            model_name='person',
            name='day_salary',
        ),
        migrations.RemoveField(
            model_name='person',
            name='day_salary_sum',
        ),
        migrations.RemoveField(
            model_name='person',
            name='hour_salary',
        ),
        migrations.RemoveField(
            model_name='person',
            name='monthly_salary',
        ),
        migrations.RemoveField(
            model_name='person',
            name='monthly_salary_sum',
        ),
        migrations.RemoveField(
            model_name='person',
            name='times_per_month',
        ),
        migrations.RemoveField(
            model_name='person',
            name='weekly_salary',
        ),
        migrations.RemoveField(
            model_name='person',
            name='weekly_salary_sum',
        ),
        migrations.AddField(
            model_name='personhourspay',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcations.Person', verbose_name='Υπάλληλος'),
        ),
        migrations.AddField(
            model_name='personhourscreate',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcations.Person', verbose_name='Υπάλληλος'),
        ),
        migrations.AddField(
            model_name='paypersonsalarycost',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcations.Person', verbose_name='Υπάλληλος'),
        ),
        migrations.AddField(
            model_name='createpersonsalarycost',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcations.Person', verbose_name='Υπάλληλος'),
        ),
    ]
