# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcations', '0006_auto_20160529_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpersonsalarycost',
            name='paid_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Αξία'),
        ),
        migrations.AddField(
            model_name='occupation',
            name='remaining_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Υπόλοιπο'),
        ),
    ]
