# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcations', '0007_auto_20160529_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpersonsalarycost',
            name='paid_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Πληρωμένο Ποσό'),
        ),
        migrations.AlterField(
            model_name='createpersonsalarycost',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Αξία'),
        ),
    ]
