# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transcations', '0009_pagia_exoda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagia_Exoda_Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Αρ.Παραστατικού')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Λήξης')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Αξία')),
                ('credit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Υπόλοιπο')),
                ('active', models.CharField(choices=[('a', 'Απλήρωτη'), ('b', 'Πληρώθηκε')], default='a', max_length=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcations.Pagia_Exoda', verbose_name='Λογαριασμός')),
            ],
        ),
    ]
