# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-24 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transcations', '0010_pagia_exoda_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagia_Exoda_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Αρ.Παραστατικού')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Λήξης')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Αξία')),
                ('credit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Υπόλοιπο')),
                ('active', models.CharField(choices=[('a', 'Απλήρωτη'), ('b', 'Πληρώθηκε')], default='a', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pagia_Exoda_Pay_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Περιγραφή')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Αξία')),
                ('day_added', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Αποδείξη Πληρωμής Πάγια',
            },
        ),
        migrations.CreateModel(
            name='PersonMastoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Εταιρία/Ονοματεπώνυμο')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Τηλέφωνο')),
                ('phone1', models.CharField(blank=True, max_length=10, null=True, verbose_name='Κινητό')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Συνολικά Έξοδα')),
                ('remaining_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Πιστωτικό Υπόλοιπο')),
            ],
        ),
        migrations.RemoveField(
            model_name='pagia_exoda_cost',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='createpersonsalarycost',
            options={'verbose_name': 'Εντολές Πληρωμής Υπαλλήλων. '},
        ),
        migrations.AlterModelOptions(
            name='fixed_costs',
            options={'verbose_name': 'Κεντρική Κατηγορία Εξόδων   '},
        ),
        migrations.AlterModelOptions(
            name='fixed_costs_item',
            options={'verbose_name': 'Λογαριασμοί και Πάγια έξοδα'},
        ),
        migrations.AlterModelOptions(
            name='occupation',
            options={'verbose_name': 'Απασχόληση   '},
        ),
        migrations.AlterModelOptions(
            name='order_fixed_cost',
            options={'verbose_name': 'Εντολές Πληρωμών'},
        ),
        migrations.AlterModelOptions(
            name='payorderfixedcost',
            options={'verbose_name': 'Αποδείξη Πληρωμής'},
        ),
        migrations.AlterModelOptions(
            name='paypersonsalarycost',
            options={'verbose_name': 'Αποδείξη Πληρωμής Υπαλλήλων'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Υπάλληλος   '},
        ),
        migrations.AlterModelOptions(
            name='personhourscreate',
            options={'verbose_name': 'Εντολές Πληρωμών-Not Working'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='salary_remaining',
        ),
        migrations.AddField(
            model_name='person',
            name='salary_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Πιστωτικό Υπόλοιπο'),
        ),
        migrations.AlterField(
            model_name='createpersonsalarycost',
            name='paid_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Πιστωτικό Υπόλοιπο'),
        ),
        migrations.AlterField(
            model_name='createpersonsalarycost',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Περιγραφή'),
        ),
        migrations.AlterField(
            model_name='fixed_costs',
            name='total_dept',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Χρεωστικό Υπόλοιπο'),
        ),
        migrations.AlterField(
            model_name='fixed_costs',
            name='total_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Πιστωτικό Υπόλοιπο'),
        ),
        migrations.AlterField(
            model_name='fixed_costs_item',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='Ονομασία Κατηγορίας'),
        ),
        migrations.AlterField(
            model_name='fixed_costs_item',
            name='total_dept',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Χρεωστικό Υπόλοιπο'),
        ),
        migrations.AlterField(
            model_name='fixed_costs_item',
            name='total_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Πιστωτικό Υπόλοιπο'),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='remaining_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Πιστωτικό Υπόλοιπο'),
        ),
        migrations.AlterField(
            model_name='order_fixed_cost',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Πιστωτικό Υπόλοιπο'),
        ),
        migrations.AlterField(
            model_name='order_fixed_cost',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ποσό Πληρωμής'),
        ),
        migrations.AlterField(
            model_name='order_fixed_cost',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Αρ.Παραστατικού/Σχολιασμός'),
        ),
        migrations.AlterField(
            model_name='pagia_exoda',
            name='remaining_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Πιστωτικό Υπόλοιπο'),
        ),
        migrations.AlterField(
            model_name='payorderfixedcost',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Αρ.Παραστατικού'),
        ),
        migrations.DeleteModel(
            name='Pagia_Exoda_Cost',
        ),
        migrations.AddField(
            model_name='pagia_exoda_pay_order',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcations.PersonMastoras', verbose_name='Εταιρία'),
        ),
        migrations.AddField(
            model_name='pagia_exoda_order',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcations.Pagia_Exoda', verbose_name='Λογαριασμός'),
        ),
        migrations.AddField(
            model_name='pagia_exoda_order',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transcations.PersonMastoras', verbose_name='Εταιρία'),
        ),
    ]
