# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcations', '0011_auto_20160624_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmastoras',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Απασχόληση'),
        ),
    ]
