# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0018_auto_20160807_1433'),
        ('transcations', '0012_personmastoras_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_fixed_cost',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_manager.PaymentMethod'),
        ),
    ]
