# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0018_auto_20160807_1433'),
        ('transcations', '0014_auto_20160810_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagia_exoda_order',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_manager.PaymentMethod', verbose_name='Τρόπος Πληρωμής'),
        ),
    ]
