# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-11 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcations', '0017_auto_20160810_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Τηλέφωνο'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone1',
            field=models.CharField(blank=True, max_length=10, verbose_name='Κινητό'),
        ),
    ]
