# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-01 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcations', '0019_auto_20160919_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='hour_salary_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Υπόλοιπο Υπερωρίων'),
        ),
        migrations.AlterField(
            model_name='person',
            name='salary_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Πιστωτικό Υπόλοιπο'),
        ),
        migrations.AlterField(
            model_name='person',
            name='total_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Συνολική Πληρωμή'),
        ),
    ]
