# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-07 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcations', '0020_auto_20170701_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Ολοκληρώθηκε')),
                ('date_started', models.DateField()),
                ('date_end', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['status', 'date_started', 'date_end'],
            },
        ),
        migrations.CreateModel(
            name='VacationReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='vacation',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transcations.VacationReason'),
        ),
        migrations.AddField(
            model_name='vacation',
            name='staff_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='transcations.Person'),
        ),
    ]
