# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-29 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletteremail',
            name='member_rating',
            field=models.IntegerField(default=3),
        ),
    ]
