# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-02 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddEsoda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.DateField(unique=True, verbose_name='Ημερομηνία')),
                ('topiko_katastima', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Τοπικο Κατάστημα')),
                ('pediko', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Παιδικό Μολάοι')),
                ('skala', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Σκάλα')),
                ('sinolo_fisikon', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Σύνολο Φυσίκων')),
                ('mymoda', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='MyModa')),
                ('sinolo_olon', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Όλα τα Έσοδα')),
            ],
        ),
        migrations.CreateModel(
            name='Katastima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24, verbose_name='Ονομασία Καταστήματος')),
            ],
        ),
        migrations.CreateModel(
            name='MonthEsoda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='July', max_length=64)),
                ('topiko_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('paidiko_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('skala_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fisika_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('my_moda_incoome', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ola_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('a', 'Σε εξέλιξη'), ('b', 'Εκλεισε')], default='a', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='YearEsoda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='2016', max_length=64, unique=True)),
                ('topiko_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('paidiko_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('skala_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fisika_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('my_moda_incoome', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ola_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('a', 'Σε εξέλιξη'), ('b', 'Εκλεισε')], default='a', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='monthesoda',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='esoda_katastimata.YearEsoda'),
        ),
        migrations.AddField(
            model_name='addesoda',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esoda_katastimata.MonthEsoda'),
        ),
        migrations.AddField(
            model_name='addesoda',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esoda_katastimata.YearEsoda'),
        ),
    ]
