# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-03 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esoda_katastimata', '0002_auto_20160703_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearesoda',
            name='title',
            field=models.CharField(default='2016', max_length=64),
        ),
    ]
