# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-16 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esoda_katastimata', '0004_auto_20160703_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addesoda',
            name='mymoda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='MyModa'),
        ),
        migrations.AlterField(
            model_name='addesoda',
            name='pediko',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Παιδικό'),
        ),
        migrations.AlterField(
            model_name='addesoda',
            name='sinolo_fisikon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Σύνολο Φυσίκων'),
        ),
        migrations.AlterField(
            model_name='addesoda',
            name='sinolo_olon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Όλα τα Έσοδα'),
        ),
        migrations.AlterField(
            model_name='addesoda',
            name='skala',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Σκάλα'),
        ),
        migrations.AlterField(
            model_name='addesoda',
            name='topiko_katastima',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Β Υποκατάστημα'),
        ),
        migrations.AlterField(
            model_name='monthesoda',
            name='title',
            field=models.CharField(default='September', max_length=64),
        ),
    ]
