# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-07 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esoda_katastimata', '0005_auto_20160916_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(default=2)),
            ],
        ),
        migrations.AlterField(
            model_name='monthesoda',
            name='title',
            field=models.CharField(default='December', max_length=64),
        ),
    ]
