# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-09 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esoda_katastimata', '0007_auto_20170609_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='addesoda',
            name='boom',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Boom'),
        ),
    ]
