# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-01 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esoda_katastimata', '0008_addesoda_boom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthesoda',
            name='title',
            field=models.CharField(default='July', max_length=64),
        ),
    ]
