# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-29 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esoda_katastimata', '0009_auto_20170701_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthesoda',
            name='title',
            field=models.CharField(default='September', max_length=64),
        ),
    ]
