# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-06 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esoda_katastimata', '0011_auto_20171021_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearesoda',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthesoda',
            name='title',
            field=models.CharField(default='April', max_length=64),
        ),
        migrations.AlterField(
            model_name='yearesoda',
            name='title',
            field=models.CharField(default='2018', max_length=64, unique=True),
        ),
    ]
