# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('a', 'Διαθέσιμο'), ('b', 'Παραγγελία σε εξέλιξη'), ('c', 'Απενεργοποιημένπ')], default='a', max_length=1)),
            ],
        ),
    ]
