# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PoS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestoOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=django.utils.timezone.now, max_length=50)),
                ('day_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('discount', models.IntegerField(default=0, verbose_name='Έκπτωση')),
                ('notes', models.TextField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Αξία Παραγγελίας')),
                ('paid_value', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Αποπληρωμένο Πόσο')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PoS.Table', verbose_name='Τραπέζι')),
            ],
        ),
    ]
