# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoS', '0003_restoorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='restoorder',
            name='status',
            field=models.CharField(choices=[('a', 'Σε εξέλιξη'), ('b', 'Αποπληρώθηκε'), ('c', 'Ακύρωση')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='restoorderitem',
            name='qty',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3, verbose_name='Ποσότητα'),
        ),
    ]
