# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-24 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PoS', '0004_auto_20160531_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyIncomeGreG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='2016-06-24', max_length=64, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('money_income', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('money_outcome', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('order_number', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('a', 'Σε εξέλιξη'), ('b', 'Εκλεισε')], default='a', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyIncomeGreG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='June', max_length=64)),
                ('money_income', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('money_outcome', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('order_number', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('a', 'Σε εξέλιξη'), ('b', 'Εκλεισε')], default='a', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserInputIncomeSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('date_done', models.DateField(default=django.utils.timezone.now)),
                ('money_income', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('money_outcome', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('order_number', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('a', 'Σε εξέλιξη'), ('b', 'Εκλεισε')], default='a', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='YearlyIncomeGreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='2016', max_length=64, unique=True)),
                ('money_income', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('money_outcome', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('order_number', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('a', 'Σε εξέλιξη'), ('b', 'Εκλεισε')], default='a', max_length=1)),
            ],
        ),
    ]
