# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-24 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PoS', '0005_dailyincomegreg_monthlyincomegreg_userinputincomeseason_yearlyincomegreg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restoorder',
            options={'verbose_name': 'Παραγγελία Εστιατορίου'},
        ),
        migrations.AlterModelOptions(
            name='restoorderitem',
            options={'verbose_name': 'Συστατικά Παραγγελίας Εστιατορίου'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Τραπέζια'},
        ),
        migrations.AddField(
            model_name='restoorder',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PoS.DailyIncomeGreG'),
        ),
        migrations.AddField(
            model_name='restoorder',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PoS.MonthlyIncomeGreG'),
        ),
        migrations.AddField(
            model_name='restoorder',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Συνολικό Κόστος Παραγγελίας'),
        ),
        migrations.AddField(
            model_name='restoorder',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PoS.YearlyIncomeGreg'),
        ),
        migrations.AddField(
            model_name='restoorderitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
