# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-24 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160624_1014'),
        ('PoS', '0006_auto_20160624_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lianiki_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=django.utils.timezone.now, max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('day_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('discount', models.IntegerField(default=0, verbose_name='Έκπτωση')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Αξία Παραγγελίας')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Συνολικό Κόστος Παραγγελίας')),
                ('paid_value', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Αποπληρωμένο Πόσο')),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PoS.DailyIncomeGreG')),
                ('month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PoS.MonthlyIncomeGreG')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PoS.YearlyIncomeGreg')),
            ],
        ),
        migrations.CreateModel(
            name='LianikiOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=1, default=1, max_digits=3, verbose_name='Ποσότητα')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PoS.Lianiki_Order')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
