# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-26 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PoS', '0008_auto_20160626_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyincomegreg',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PoS.MonthlyIncomeGreG'),
        ),
        migrations.AddField(
            model_name='dailyincomegreg',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PoS.YearlyIncomeGreg'),
        ),
        migrations.AddField(
            model_name='monthlyincomegreg',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PoS.YearlyIncomeGreg'),
        ),
    ]
