# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoS', '0009_auto_20160626_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyincomegreg',
            name='title',
            field=models.CharField(default='2016-06-28', max_length=64, unique=True),
        ),
    ]
