# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-20 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoS', '0010_auto_20160628_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyincomegreg',
            name='title',
            field=models.CharField(default='2016-07-20', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='lianikiorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Τιμή Μονάδας'),
        ),
        migrations.AlterField(
            model_name='monthlyincomegreg',
            name='title',
            field=models.CharField(default='July', max_length=64),
        ),
    ]
