# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-21 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoS', '0011_auto_20160720_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyincomegreg',
            name='title',
            field=models.CharField(default='2016-07-21', max_length=64, unique=True),
        ),
    ]
