# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-31 06:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoS', '0014_auto_20160731_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lianiki_order',
            name='day_added',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 31, 9, 51, 15, 37116)),
        ),
        migrations.AlterField(
            model_name='lianiki_order',
            name='title',
            field=models.CharField(default=datetime.datetime(2016, 7, 31, 9, 51, 15, 37116), max_length=50),
        ),
    ]
