# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 10:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoS', '0016_auto_20160731_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lianiki_order',
            name='day_added',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 31, 13, 17, 56, 103630)),
        ),
        migrations.AlterField(
            model_name='lianiki_order',
            name='title',
            field=models.CharField(default=datetime.datetime(2016, 7, 31, 13, 17, 56, 102627), max_length=50),
        ),
    ]
