# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 10:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoS', '0017_auto_20160731_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lianiki_order',
            name='day_added',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 31, 13, 27, 53, 107904)),
        ),
        migrations.AlterField(
            model_name='lianiki_order',
            name='title',
            field=models.CharField(default=datetime.datetime(2016, 7, 31, 13, 27, 53, 107404), max_length=50),
        ),
    ]
