# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-12 22:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoS', '0036_auto_20160813_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lianiki_order',
            name='day_added',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 13, 1, 26, 13, 832616)),
        ),
        migrations.AlterField(
            model_name='lianiki_order',
            name='title',
            field=models.CharField(default=datetime.datetime(2016, 8, 13, 1, 26, 13, 832616), max_length=50),
        ),
    ]
