# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-19 05:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoS', '0042_auto_20160819_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lianiki_order',
            name='day_added',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 19, 8, 58, 40, 811782)),
        ),
        migrations.AlterField(
            model_name='lianiki_order',
            name='title',
            field=models.CharField(default=datetime.datetime(2016, 8, 19, 8, 58, 40, 811782), max_length=50),
        ),
    ]
