# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-19 06:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoS', '0043_auto_20160819_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lianiki_order',
            name='day_added',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 19, 9, 32, 29, 278420)),
        ),
        migrations.AlterField(
            model_name='lianiki_order',
            name='title',
            field=models.CharField(default=datetime.datetime(2016, 8, 19, 9, 32, 29, 278420), max_length=50),
        ),
    ]
