# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-04 06:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20160904_0941'),
        ('PoS', '0051_auto_20160823_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailReturnItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Τιμή Μονάδας')),
                ('qty', models.DecimalField(decimal_places=1, default=1, max_digits=3, verbose_name='Ποσότητα')),
            ],
        ),
        migrations.CreateModel(
            name='RetailReturnOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.DateField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='dailyincomegreg',
            name='title',
            field=models.CharField(default='2016-09-04', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='lianiki_order',
            name='day_added',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 4, 9, 40, 58, 243071)),
        ),
        migrations.AlterField(
            model_name='lianiki_order',
            name='title',
            field=models.CharField(default=datetime.datetime(2016, 9, 4, 9, 40, 58, 243071), max_length=50),
        ),
        migrations.AlterField(
            model_name='monthlyincomegreg',
            name='title',
            field=models.CharField(default='September', max_length=64),
        ),
        migrations.AddField(
            model_name='retailreturnitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PoS.RetailReturnOrder'),
        ),
        migrations.AddField(
            model_name='retailreturnitem',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
