# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-04 13:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20160904_0941'),
        ('PoS', '0052_auto_20160904_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='lianikiorderitem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ColorAttribute'),
        ),
        migrations.AddField(
            model_name='lianikiorderitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.SizeAttribute'),
        ),
        migrations.AlterField(
            model_name='lianiki_order',
            name='day_added',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 4, 16, 59, 39, 180049)),
        ),
        migrations.AlterField(
            model_name='lianiki_order',
            name='title',
            field=models.CharField(default=datetime.datetime(2016, 9, 4, 16, 59, 39, 180049), max_length=50),
        ),
    ]
