# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-09 15:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoS', '0063_auto_20161207_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyincomegreg',
            name='title',
            field=models.CharField(default='2017-06-09', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='lianiki_order',
            name='day_added',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 9, 18, 32, 52, 762328)),
        ),
        migrations.AlterField(
            model_name='lianiki_order',
            name='title',
            field=models.CharField(default=datetime.datetime(2017, 6, 9, 18, 32, 52, 762328), max_length=50),
        ),
        migrations.AlterField(
            model_name='monthlyincomegreg',
            name='title',
            field=models.CharField(default='June', max_length=64),
        ),
        migrations.AlterField(
            model_name='yearlyincomegreg',
            name='title',
            field=models.CharField(default='2017', max_length=64, unique=True),
        ),
    ]
