# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-09 15:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoS', '0064_auto_20170609_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lianiki_order',
            name='day_added',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 9, 18, 44, 31, 44684)),
        ),
        migrations.AlterField(
            model_name='lianiki_order',
            name='title',
            field=models.CharField(default=datetime.datetime(2017, 6, 9, 18, 44, 31, 44684), max_length=50),
        ),
    ]
