# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-06 12:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoS', '0069_auto_20171021_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyincomegreg',
            name='title',
            field=models.CharField(default='2018-04-06', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='lianiki_order',
            name='day_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 6, 15, 44, 53, 493865)),
        ),
        migrations.AlterField(
            model_name='lianiki_order',
            name='title',
            field=models.CharField(default=datetime.datetime(2018, 4, 6, 15, 44, 53, 493865), max_length=50),
        ),
        migrations.AlterField(
            model_name='monthlyincomegreg',
            name='title',
            field=models.CharField(default='April', max_length=64),
        ),
        migrations.AlterField(
            model_name='yearlyincomegreg',
            name='title',
            field=models.CharField(default='2018', max_length=64, unique=True),
        ),
    ]
