# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-06 12:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoS', '0070_auto_20180406_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lianiki_order',
            name='day_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 6, 15, 49, 16, 603137)),
        ),
        migrations.AlterField(
            model_name='lianiki_order',
            name='title',
            field=models.CharField(default=datetime.datetime(2018, 4, 6, 15, 49, 16, 603137), max_length=50),
        ),
    ]
