# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-07 14:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoS', '0071_auto_20180406_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyincomegreg',
            name='title',
            field=models.CharField(default='2018-06-07', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='lianiki_order',
            name='day_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 7, 17, 0, 56, 84519)),
        ),
        migrations.AlterField(
            model_name='lianiki_order',
            name='title',
            field=models.CharField(default=datetime.datetime(2018, 6, 7, 17, 0, 56, 84519), max_length=50),
        ),
        migrations.AlterField(
            model_name='monthlyincomegreg',
            name='title',
            field=models.CharField(default='June', max_length=64),
        ),
    ]
