# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-14 10:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoS', '0072_auto_20180607_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyincomegreg',
            name='title',
            field=models.CharField(default='2018-06-14', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='lianiki_order',
            name='day_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 14, 13, 23, 33, 826049)),
        ),
        migrations.AlterField(
            model_name='lianiki_order',
            name='title',
            field=models.CharField(default=datetime.datetime(2018, 6, 14, 13, 23, 33, 826049), max_length=50),
        ),
    ]
