# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_focus', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['title', 'sub_category'],
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('id_focus', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['id_focus', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=62, unique=True, verbose_name='Όνομα Συνταγής')),
                ('active', models.CharField(choices=[('a', 'Ενεργό'), ('i', 'Μη Ενεργό')], default='a', max_length=1, verbose_name='Κατάσταση')),
                ('description', models.TextField(blank=True, verbose_name='Πληροφορίες')),
                ('recipe_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Κόστος Παραγωγής')),
                ('recipe_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Τιμή Πωλησης')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.MainCategory', verbose_name='Κατηγορία')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_part', models.CharField(max_length=64, verbose_name='Συστατικό')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Ποσότητα σε κιλά')),
                ('price_cost', models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Κόστος')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Προιόν ')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe', verbose_name='Συνταγή')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('id_focus', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['id_focus', 'title'],
            },
        ),
        migrations.AddField(
            model_name='maincategory',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.SecondaryCategory'),
        ),
        migrations.AddField(
            model_name='categorycata',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.SecondaryCategory'),
        ),
        migrations.AddField(
            model_name='categorycata',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.MainCategory'),
        ),
    ]
