# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-24 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'ordering': ['id_focus', 'title'], 'verbose_name': 'Κεντρική Κατηγορία Menu.'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Συνταγή    '},
        ),
        migrations.AlterModelOptions(
            name='recipeitem',
            options={'verbose_name': 'Συστατικά Συνταγής   '},
        ),
        migrations.AddField(
            model_name='maincategory',
            name='active',
            field=models.CharField(choices=[('a', 'Ενεργό'), ('i', 'Μη Ενεργό')], default='a', max_length=1, verbose_name='Κατάσταση'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='costum_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Επιλογή χρήστη κόστος'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='costum_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Επιλογή χρήστη κόστος'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='day_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ημερήσιο Κόστος'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='day_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ημερήσιο Κόστος'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='month_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Μηνιαίο κόστος'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='month_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Μηνιαίο κόστος'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='yearly_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Έτος κόστος'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='yearly_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Έτος κόστος'),
        ),
    ]
