# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-26 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0003_auto_20160624_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payorders',
            name='value_portion',
            field=models.CharField(choices=[('a', 'Εξόφληση συνολικής αξιας'), ('b', 'Δόσεις')], default='b', max_length=1, verbose_name='Τρόπος Πληρωμής'),
        ),
    ]
