# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-31 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0004_auto_20160626_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Εκπτωση'),
        ),
    ]
