# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20160731_1010'),
        ('inventory_manager', '0007_auto_20160731_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ποσότητα')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_manager.OrderItem')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ColorAttribute')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_manager.PaymentMethod', verbose_name='Τρόπος Πληρωμής'),
        ),
    ]
