# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0008_auto_20160801_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemcolor',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ποσότητα'),
        ),
    ]
