# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-04 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_supply_remaining_deposit'),
        ('inventory_manager', '0009_auto_20160802_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDepositOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('day_added', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentmethodgroup',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vendordepositorder',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_manager.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='vendordepositorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Supply'),
        ),
    ]
