# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-05 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0010_auto_20160804_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDepositOrderPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('day_added', models.DateField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_manager.Order')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_manager.PaymentMethod')),
            ],
        ),
    ]
