# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-07 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0011_vendordepositorderpay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendordepositorder',
            name='title',
        ),
        migrations.AddField(
            model_name='vendordepositorder',
            name='title_de',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
