# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-07 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0012_auto_20160807_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendordepositorderpay',
            old_name='title',
            new_name='title_de',
        ),
    ]
