# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-07 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0015_auto_20160807_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendordepositorder',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vendordepositorderpay',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
