# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-07 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0017_payorders_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendordepositorder',
            old_name='title_de',
            new_name='title',
        ),
    ]
