# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-12 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0018_auto_20160807_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=255, verbose_name='Ποσό')),
                ('debtor', models.CharField(max_length=64)),
                ('date_expire', models.DateField(auto_now=True)),
                ('date_added', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('a', 'Σε εξέλιξη'), ('b', 'Εισπράκτηκε'), ('c', 'Ακυρώθηκε')], max_length=1)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_manager.PaymentMethod')),
            ],
        ),
    ]
