# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-12 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0019_checkorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkorder',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Supply'),
        ),
    ]
