# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-12 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0020_auto_20160813_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkorder',
            name='status',
            field=models.CharField(choices=[('a', 'Σε εξέλιξη'), ('b', 'Εισπράκτηκε'), ('c', 'Ακυρώθηκε')], default='a', max_length=1),
        ),
    ]
