# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-13 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0021_auto_20160813_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkorder',
            name='date_expire',
            field=models.DateField(),
        ),
    ]
