# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-19 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0024_auto_20160813_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkorder',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Supply', verbose_name='Πιστωτής'),
        ),
        migrations.AlterField(
            model_name='checkorder',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_manager.PaymentMethod', verbose_name='Τόπος- Τράπεζα'),
        ),
        migrations.AlterField(
            model_name='checkorder',
            name='status',
            field=models.CharField(choices=[('a', 'Σε εξέλιξη'), ('b', 'Εισπράκτηκε'), ('c', 'Ακυρώθηκε')], default='a', max_length=1, verbose_name='Κατάσταση'),
        ),
        migrations.AlterField(
            model_name='checkorder',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Σχόλια'),
        ),
    ]
