# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-04 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0026_auto_20160823_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkorder',
            name='date_expire',
            field=models.DateField(verbose_name='Ημερομηνία Λήξης'),
        ),
    ]
