# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-09 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0028_auto_20160911_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkorder',
            options={'ordering': ['-date_expire']},
        ),
    ]
