# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Costumers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, unique=True, verbose_name='Ονομα/Επωνυμία')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Περιγραφή')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Τηλέφωνο')),
                ('phone1', models.CharField(blank=True, max_length=10, null=True, verbose_name='Τηλέφωνο')),
                ('fax', models.CharField(blank=True, max_length=10, null=True, verbose_name='Fax')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('site', models.CharField(blank=True, max_length=40, null=True, verbose_name='Site')),
                ('address', models.CharField(blank=True, max_length=40, null=True, verbose_name='Διεύθυνση')),
                ('balance', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Υπόλοιπο')),
                ('afm', models.CharField(blank=True, max_length=9, null=True, verbose_name='ΑΦΜ')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, unique=True, verbose_name="'Ονομα προιόντος")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Κωδικός Τιμολογίου')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Τιμή λιανικής')),
                ('price_internet', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Τιμή Χονδρικής')),
                ('price_buy', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Τιμή Αγοράς')),
                ('image', models.FileField(blank=True, null=True, upload_to=products.models.my_awesome_upload_function)),
                ('status', models.CharField(choices=[('a', 'Σε απόθεμα'), ('i', 'Inactive'), ('o', 'Διαθέσιμο με παραγγελία'), ('p', 'Προσωρινά μη διαθέσιμο')], default='a', max_length=1, verbose_name='Κατάσταση')),
                ('carousel', models.CharField(choices=[('a', 'Active'), ('n', 'Not active')], default='n', max_length=1, verbose_name='Υπερχονδρική')),
                ('reserve', models.IntegerField(default=0, verbose_name='Απόθεμα')),
                ('product_id', models.CharField(blank=True, max_length=6, null=True, verbose_name='Κωδικός/Barcode')),
                ('ekptosi', models.IntegerField(blank=True, default=0, max_length=3, null=True)),
                ('day_added', models.DateField(default=django.utils.timezone.now)),
                ('qty_kilo', models.DecimalField(decimal_places=3, default=1, max_digits=5, verbose_name='Βάρος Συσκευασίας σε κιλά.')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Περιγραφή')),
                ('price_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
                ('costumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Costumers', verbose_name='Πελάτης')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, unique=True, verbose_name="'Ονομα")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Περιγραφή')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Τηλέφωνο')),
                ('phone1', models.CharField(blank=True, max_length=10, null=True, verbose_name='Τηλέφωνο')),
                ('fax', models.CharField(blank=True, max_length=10, null=True, verbose_name='Fax')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('site', models.CharField(blank=True, max_length=40, null=True, verbose_name='Site')),
                ('address', models.CharField(blank=True, max_length=40, null=True, verbose_name='Διεύθυνση')),
                ('balance', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Υπόλοιπο')),
                ('afm', models.CharField(blank=True, max_length=9, null=True, verbose_name='ΑΦΜ')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TaxesCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='supply',
            name='doy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.TaxesCity', verbose_name='Εφορία'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Supply', verbose_name='Προμηθευτής'),
        ),
        migrations.AddField(
            model_name='costumers',
            name='DOY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.TaxesCity', verbose_name='Εφορία'),
        ),
    ]
