# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-24 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Κατηγορίες  '},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'verbose_name': 'Προϊόντα    '},
        ),
        migrations.AlterModelOptions(
            name='supply',
            options={'ordering': ['title'], 'verbose_name': 'Προμηθευτές   '},
        ),
        migrations.AlterModelOptions(
            name='taxescity',
            options={'verbose_name': 'ΔΟΥ   '},
        ),
        migrations.AddField(
            model_name='product',
            name='safe_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='reserve',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Απόθεμα'),
        ),
    ]
