# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-26 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160624_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ekptosi',
            field=models.IntegerField(blank=True, default=0, max_length=3, null=True, verbose_name="'Εκπτωση Τιμολογίου σε %"),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty_kilo',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=5, verbose_name='Βάρος/Τεμάχια ανά Συσκευασία '),
        ),
    ]
