# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-20 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20160626_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Attributes_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('qty', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='site_active',
            field=models.CharField(default='b', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='data',
            field=models.ManyToManyField(blank=True, null=True, to='products.Attributes_data'),
        ),
        migrations.AddField(
            model_name='product',
            name='attribute',
            field=models.ManyToManyField(blank=True, null=True, to='products.Attributes_data'),
        ),
    ]
