# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-20 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20160720_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='qty',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
