# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-20 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_attribute_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='data',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'verbose_name_plural': 'Προϊόντα'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='attribute',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='Attributes_data',
        ),
    ]
