# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-31 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20160721_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('a', 'True'), ('b', 'False')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('a', 'True'), ('b', 'False')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='site_active',
            field=models.CharField(choices=[('a', 'Ενεργοποιημένο'), ('b', 'Απενεργοποιημένο')], default='b', max_length=1, null=True),
        ),
    ]
