# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-31 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20160731_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ekptosi',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="'Εκπτωση Τιμολογίου σε %"),
        ),
    ]
