# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-04 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20160731_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='remaining_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Υπόλοιπο προκαταβολών'),
        ),
    ]
