# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-19 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_supply_remaining_deposit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='site_active',
            new_name='ware_active',
        ),
    ]
