# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-21 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20160820_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='status',
            field=models.CharField(choices=[('a', 'Ενεργό'), ('b', 'Μη Ενεργό')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='Ονομασία Χρώματος'),
        ),
    ]
