# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-21 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20160821_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='status',
            field=models.CharField(choices=[('a', 'Ενεργό'), ('b', 'Μη Ενεργό')], default='a', max_length=1, verbose_name='Κατάσταση'),
        ),
        migrations.AlterField(
            model_name='color',
            name='status',
            field=models.CharField(choices=[('a', 'Ενεργό'), ('b', 'Μη Ενεργό')], default='a', max_length=1, verbose_name='Κατάσταση'),
        ),
    ]
