# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-21 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20160821_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorattribute',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='Ονομασία Μεγέθους'),
        ),
    ]
