# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-23 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20160821_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorattribute',
            name='order_discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="'Εκπτωση Τιμολογίου σε %"),
        ),
        migrations.AddField(
            model_name='colorattribute',
            name='price_buy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Τιμή Αγοράς'),
        ),
        migrations.AddField(
            model_name='sizeattribute',
            name='order_discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="'Εκπτωση Τιμολογίου σε %"),
        ),
        migrations.AddField(
            model_name='sizeattribute',
            name='price_buy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Τιμή Αγοράς'),
        ),
    ]
