# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-04 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20160823_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Περιγραφή'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=70, unique=True, verbose_name='Τίτλος Κατηγορίας'),
        ),
        migrations.AlterUniqueTogether(
            name='colorattribute',
            unique_together=set([('title', 'product')]),
        ),
    ]
