# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-07 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_changeqtyorder_changeqtyorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeqtyorder',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='Σχολιασμός'),
        ),
    ]
