# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-15 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20160908_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeQtyOrderItemColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ChangeQtyOrder')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ColorAttribute')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeQtyOrderItemSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ChangeQtyOrder')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.SizeAttribute')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('a', 'True'), ('b', 'False')], default='b', max_length=1, verbose_name='Μεγεθολόγιο Χρωμάτων'),
        ),
        migrations.AlterField(
            model_name='product',
            name='day_added',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Δημιουργίας'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('a', 'True'), ('b', 'False')], default='b', max_length=1, verbose_name='Μεγεθολόγιο Μεγεθών'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ware_active',
            field=models.CharField(choices=[('a', 'Ενεργοποιημένο'), ('b', 'Απενεργοποιημένο')], default='a', max_length=1, null=True, verbose_name='Κατάσταση'),
        ),
    ]
